version: '3.8'

services:
  seajay-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: ${TZ:-America/Chicago}
    platform: linux/amd64  # Required for chess engine development
    
    # Container name based on machine to avoid conflicts
    container_name: seajay-dev-${MACHINE_NAME:-default}
    
    volumes:
      # Main workspace mount
      - ..:/workspace:delegated
      
      # Machine-specific cache directories (stored outside iCloud)
      - ${HOME}/.seajay-docker/ccache:/home/developer/.ccache
      - ${HOME}/.seajay-docker/bash_history:/home/developer/.bash_history
      - ${HOME}/.seajay-docker/zsh_history:/home/developer/.zsh_history
      - ${HOME}/.seajay-docker/config:/home/developer/.config
      
      # VS Code server directory (machine-specific)
      - ${HOME}/.seajay-docker/vscode-server:/home/developer/.vscode-server
      - ${HOME}/.seajay-docker/vscode-server-insiders:/home/developer/.vscode-server-insiders
    
    environment:
      - WORKSPACE=/workspace
      - EXTERNAL_DIR=/workspace/external
      - MAKEFLAGS=-j$${NPROC:-4}
      - CLAUDE_CONFIG_DIR=/home/developer/.config/claude
      - CXXFLAGS=-march=x86-64-v3
      - ASAN_OPTIONS=symbolize=1:print_stats=1:check_initialization_order=1
      - UBSAN_OPTIONS=print_stacktrace=1:halt_on_error=1
      - SEAJAY_TEST_SUITE=/workspace/tests/positions
      - MACHINE_NAME=${MACHINE_NAME:-default}
    
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    shm_size: 2gb
    
    # Keep container running
    command: /bin/sh -c "while sleep 1000; do :; done"
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 12G
        reservations:
          cpus: '2'
          memory: 6G